# Generated by Django 5.1.7 on 2025-03-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(null=True, upload_to='passports/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(null=True, upload_to='passports/')),
                ('phone_number', models.CharField(max_length=100)),
                ('email_address', models.EmailField(default='Not provided yet', max_length=254)),
                ('website', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers_license',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Unknown', max_length=250)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('placeofbirth', models.CharField(max_length=250)),
                ('profile_pic', models.ImageField(null=True, upload_to='passports/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(default='Unknown', max_length=250)),
                ('phone_number', models.CharField(max_length=11)),
                ('license_number', models.CharField(default='Unknown', max_length=50)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('license_type', models.CharField(default='Unknown', max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NIN_IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Unknown', max_length=250)),
                ('profile_pic', models.ImageField(null=True, upload_to='passports/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Unknown', max_length=1)),
                ('address', models.CharField(default='Unknown', max_length=250)),
                ('nin', models.CharField(max_length=11)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('state_of_origin', models.CharField(default='Unknown', max_length=250)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
