# Generated by Django 5.1.7 on 2025-03-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_card_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_id',
            name='website',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
