# Generated by Django 5.1.7 on 2025-04-09 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id_card_app', '0002_alter_business_id_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nin_idcard',
            name='nin',
        ),
    ]
